from PikaObj import *

def audioPlayUrl(url:str): ...
def audioPlayPause(): ...
def audioPlayStop(): ...
def audioSetVol(vol:int): ...
def audioGetVol()->int: ...

class HttpClient:
	def __init__(self): ...
	def __del__(self): ...

	def seturl(self, url:str):
		pass
	def setbody(self, body:str):
		pass
	def setmethod(self, method:str):
		pass
	def start(self):
		pass
