text = "alpha,beta"
encoded = text.encode()
print(encoded)
print(encoded.decode())
print(text.find("ha"))
print(text.find("zz"))
parts = text.split(",")
print(parts[0])
print(parts[1])
print(text.startswith("alp"))
print(text.startswith("beta"))
print(text.endswith("beta"))
print(text.endswith("alpha"))
mixed = "HeAdEr"
print(mixed.lower())
print("ChAiN".lower().encode().decode())
data = b"AA|BB"
binary = data.split(b"|")
print(binary[0])
print(binary[1])
print(data.find(b"BB"))
print(data.startswith(b"AA"))
print(data.endswith(b"BB"))
print(data.endswith(b"AA"))
empty = "".split(",")
print(len(empty))
print(empty[0])
words = "  one  two three  ".split()
print(len(words))
print(words[0])
print(words[2])
limited = "a:b:c".split(":", 1)
print(limited[0])
print(limited[1])
