from typing import Any


pi: float = 3.141592653589793
e: float = 2.718281828459045


def ceil(x: Any) -> int: ...
def fabs(x: Any) -> float: ...
def floor(x: Any) -> int: ...
def fmod(x: Any, y: Any) -> float: ...
def remainder(x: Any, y: Any) -> float: ...
def trunc(x: Any) -> int: ...
def exp(x: Any) -> float: ...
def log(x: Any) -> float: ...
def log2(x: Any) -> float: ...
def log10(x: Any) -> float: ...
def pow(x: Any, y: Any) -> float: ...
def sqrt(x: Any) -> float: ...
def acos(x: Any) -> float: ...
def asin(x: Any) -> float: ...
def atan(x: Any) -> float: ...
def atan2(x: Any, y: Any) -> float: ...
def cos(x: Any) -> float: ...
def sin(x: Any) -> float: ...
def tan(x: Any) -> float: ...
def degrees(x: Any) -> float: ...
def radians(x: Any) -> float: ...
def cosh(x: Any) -> float: ...
def sinh(x: Any) -> float: ...
def tanh(x: Any) -> float: ...
