from typing import Any

ALIGN_CENTER: int = 0
ALIGN_TOP_LEFT: int = 1

def init() -> None: ...
def scr_act() -> obj: ...
def timer_handler() -> int: ...
def display_register(buffer: bytearray) -> None: ...
def input_register(state: int) -> None: ...
def driver_step() -> int: ...

class obj:
    def __init__(self, parent: Any = None) -> None: ...
    def delete(self) -> None: ...
    def set_x(self, value: int) -> None: ...
    def set_y(self, value: int) -> None: ...
    def get_x(self) -> int: ...
    def get_y(self) -> int: ...
    def align(self, target: Any, align: int, x: int, y: int) -> None: ...
    def add_event_cb(self, callback: Any, code: int, user_data: int = 0) -> None: ...
    def trigger_event(self, code: int) -> None: ...

class btn:
    def __init__(self, parent: Any = None) -> None: ...
    def delete(self) -> None: ...
    def set_x(self, value: int) -> None: ...
    def set_y(self, value: int) -> None: ...
    def get_x(self) -> int: ...
    def get_y(self) -> int: ...
    def align(self, target: Any, align: int, x: int, y: int) -> None: ...
    def add_event_cb(self, callback: Any, code: int, user_data: int = 0) -> None: ...
    def trigger_event(self, code: int) -> None: ...

class label:
    def __init__(self, parent: Any = None) -> None: ...
    def delete(self) -> None: ...
    def set_x(self, value: int) -> None: ...
    def set_y(self, value: int) -> None: ...
    def get_x(self) -> int: ...
    def get_y(self) -> int: ...
    def align(self, target: Any, align: int, x: int, y: int) -> None: ...
    def add_event_cb(self, callback: Any, code: int, user_data: int = 0) -> None: ...
    def trigger_event(self, code: int) -> None: ...
    def set_text(self, value: str) -> None: ...
    def get_text(self) -> str: ...

class timer:
    def __init__(self, callback: Any, period_ms: int, user_data: int = 0) -> None: ...
    def trigger(self) -> None: ...
    def delete(self) -> None: ...
