from typing import Any


AF_INET: int = 2
SOCK_STREAM: int = 1


def gethostbyname(host: str) -> str: ...


class Socket:
    def __init__(
        self,
        family: int = 2,
        type: int = 1,
        proto: int = 0,
    ) -> None: ...
    def bind(self, host: str, port: int) -> None: ...
    def listen(self, backlog: int = 1) -> None: ...
    def accept(self) -> Socket: ...
    def peer_host(self) -> str: ...
    def peer_port(self) -> int: ...
    def local_host(self) -> str: ...
    def local_port(self) -> int: ...
    def connect(self, host: str, port: int) -> None: ...
    def send(self, data: bytes) -> int: ...
    def sendall(self, data: bytes) -> None: ...
    def recv(self, size: int) -> bytes: ...
    def setblocking(self, flag: bool) -> None: ...
    def settimeout(self, seconds: Any) -> None: ...
    def close(self) -> None: ...
