import imp
from PikaObj import *
import json


class cJSON(TinyObj):
    def print(self) -> str: ...
    def parse(self, value: str): ...
    def __del__(self): ...
    def getObjectItem(self, string: str) -> any: ...
