pi: float
e: float


def __init__(): ...
def ceil(x: float) -> int: ...
def fabs(x: float) -> float: ...
def floor(x: float) -> int: ...
def fmod(x: float, y: float) -> float: ...
def remainder(x: float, y: float) -> float: ...
def trunc(x: float) -> float: ...
def exp(x: float) -> float: ...
def log(x: float) -> float: ...
def log2(x: float) -> float: ...
def log10(x: float) -> float: ...
def pow(x: float, y: float) -> float: ...
def sqrt(x: float) -> float: ...
def acos(x: float) -> float: ...
def asin(x: float) -> float: ...
def atan(x: float) -> float: ...
def atan2(x: float, y: float) -> float: ...
def cos(x: float) -> float: ...
def sin(x: float) -> float: ...
def tan(x: float) -> float: ...
def degrees(x: float) -> float: ...
def radians(x: float) -> float: ...
def cosh(x: float) -> float: ...
def sinh(x: float) -> float: ...
def tanh(x: float) -> float: ...
