/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * https://pikadoc.readthedocs.io/zh/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef __pika_lvgl_img__H
#define __pika_lvgl_img__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New_pika_lvgl_img(Args *args);

void pika_lvgl_img___init__(PikaObj *self, PikaObj* parent);
int pika_lvgl_img_get_angle(PikaObj *self);
int pika_lvgl_img_get_antialias(PikaObj *self);
int pika_lvgl_img_get_offset_x(PikaObj *self);
int pika_lvgl_img_get_offset_y(PikaObj *self);
int pika_lvgl_img_get_size_mode(PikaObj *self);
PikaObj* pika_lvgl_img_get_src(PikaObj *self);
int pika_lvgl_img_get_zoom(PikaObj *self);
void pika_lvgl_img_set_angle(PikaObj *self, int angle);
void pika_lvgl_img_set_antialias(PikaObj *self, int antialias);
void pika_lvgl_img_set_offset_x(PikaObj *self, int x);
void pika_lvgl_img_set_offset_y(PikaObj *self, int y);
void pika_lvgl_img_set_pivot(PikaObj *self, int x, int y);
void pika_lvgl_img_set_size_mode(PikaObj *self, int mode);
void pika_lvgl_img_set_src(PikaObj *self, PikaObj* src);
void pika_lvgl_img_set_zoom(PikaObj *self, int zoom);

#endif
