/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * https://pikadoc.readthedocs.io/zh/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef __pika_lvgl_lv_obj__H
#define __pika_lvgl_lv_obj__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New_pika_lvgl_lv_obj(Args *args);

void pika_lvgl_lv_obj___init__(PikaObj *self, PikaObj* parent);
void pika_lvgl_lv_obj_add_event_cb(PikaObj *self, Arg* event_cb, int filter, void* user_data);
void pika_lvgl_lv_obj_add_flag(PikaObj *self, int flag);
void pika_lvgl_lv_obj_add_state(PikaObj *self, int state);
void pika_lvgl_lv_obj_add_style(PikaObj *self, PikaObj* style, int selector);
void pika_lvgl_lv_obj_align(PikaObj *self, int align, int x_ofs, int y_ofs);
void pika_lvgl_lv_obj_align_to(PikaObj *self, PikaObj* base, int align, int x_ofs, int y_ofs);
void pika_lvgl_lv_obj_center(PikaObj *self);
void pika_lvgl_lv_obj_clear_flag(PikaObj *self, int flag);
int pika_lvgl_lv_obj_get_content_height(PikaObj *self);
int pika_lvgl_lv_obj_get_content_width(PikaObj *self);
int pika_lvgl_lv_obj_get_height(PikaObj *self);
char* pika_lvgl_lv_obj_get_id(PikaObj *self);
int pika_lvgl_lv_obj_get_self_height(PikaObj *self);
int pika_lvgl_lv_obj_get_self_width(PikaObj *self);
int pika_lvgl_lv_obj_get_width(PikaObj *self);
int pika_lvgl_lv_obj_get_x(PikaObj *self);
int pika_lvgl_lv_obj_get_x2(PikaObj *self);
int pika_lvgl_lv_obj_get_x_aligned(PikaObj *self);
int pika_lvgl_lv_obj_get_y(PikaObj *self);
int pika_lvgl_lv_obj_get_y2(PikaObj *self);
int pika_lvgl_lv_obj_get_y_aligned(PikaObj *self);
int pika_lvgl_lv_obj_hit_test(PikaObj *self, PikaObj* point);
void pika_lvgl_lv_obj_invalidate(PikaObj *self);
int pika_lvgl_lv_obj_is_layout_positioned(PikaObj *self);
int pika_lvgl_lv_obj_is_visible(PikaObj *self);
void pika_lvgl_lv_obj_mark_layout_as_dirty(PikaObj *self);
void pika_lvgl_lv_obj_move_children_by(PikaObj *self, int x_diff, int y_diff, int ignore_floating);
void pika_lvgl_lv_obj_move_to(PikaObj *self, int x, int y);
void pika_lvgl_lv_obj_refr_pos(PikaObj *self);
int pika_lvgl_lv_obj_refr_size(PikaObj *self);
int pika_lvgl_lv_obj_refresh_self_size(PikaObj *self);
void pika_lvgl_lv_obj_set_align(PikaObj *self, int align);
void pika_lvgl_lv_obj_set_content_height(PikaObj *self, int h);
void pika_lvgl_lv_obj_set_content_width(PikaObj *self, int w);
void pika_lvgl_lv_obj_set_ext_click_area(PikaObj *self, int size);
void pika_lvgl_lv_obj_set_flex_align(PikaObj *self, int main_place, int cross_place, int align);
void pika_lvgl_lv_obj_set_flex_flow(PikaObj *self, int flow);
void pika_lvgl_lv_obj_set_flex_grow(PikaObj *self, int value);
void pika_lvgl_lv_obj_set_height(PikaObj *self, int h);
void pika_lvgl_lv_obj_set_id(PikaObj *self, char* id);
void pika_lvgl_lv_obj_set_layout(PikaObj *self, int layout);
void pika_lvgl_lv_obj_set_pos(PikaObj *self, int x, int y);
void pika_lvgl_lv_obj_set_size(PikaObj *self, int w, int h);
void pika_lvgl_lv_obj_set_width(PikaObj *self, int w);
void pika_lvgl_lv_obj_set_x(PikaObj *self, int x);
void pika_lvgl_lv_obj_set_y(PikaObj *self, int y);
void pika_lvgl_lv_obj_transform_point(PikaObj *self, PikaObj* p, int recursive, int inv);
void pika_lvgl_lv_obj_update_layout(PikaObj *self);

#endif
