/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * https://pikadoc.readthedocs.io/zh/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef __PikaStdDevice_Time__H
#define __PikaStdDevice_Time__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New_PikaStdDevice_Time(Args *args);

void PikaStdDevice_Time___init__(PikaObj *self);
void PikaStdDevice_Time_asctime(PikaObj *self);
void PikaStdDevice_Time_ctime(PikaObj *self, pika_float unix_time);
void PikaStdDevice_Time_gmtime(PikaObj *self, pika_float unix_time);
void PikaStdDevice_Time_localtime(PikaObj *self, pika_float unix_time);
int PikaStdDevice_Time_mktime(PikaObj *self);
void PikaStdDevice_Time_platformGetTick(PikaObj *self);
void PikaStdDevice_Time_sleep(PikaObj *self, pika_float s);
void PikaStdDevice_Time_sleep_ms(PikaObj *self, int ms);
void PikaStdDevice_Time_sleep_s(PikaObj *self, int s);
pika_float PikaStdDevice_Time_time(PikaObj *self);
int PikaStdDevice_Time_time_ns(PikaObj *self);

#endif
