/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * https://pikadoc.readthedocs.io/zh/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef __PikaStdDevice_GPIO__H
#define __PikaStdDevice_GPIO__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New_PikaStdDevice_GPIO(Args *args);

void PikaStdDevice_GPIO___init__(PikaObj *self);
void PikaStdDevice_GPIO_disable(PikaObj *self);
void PikaStdDevice_GPIO_enable(PikaObj *self);
int PikaStdDevice_GPIO_getId(PikaObj *self);
char* PikaStdDevice_GPIO_getMode(PikaObj *self);
char* PikaStdDevice_GPIO_getPin(PikaObj *self);
void PikaStdDevice_GPIO_high(PikaObj *self);
void PikaStdDevice_GPIO_low(PikaObj *self);
void PikaStdDevice_GPIO_platformDisable(PikaObj *self);
void PikaStdDevice_GPIO_platformEnable(PikaObj *self);
void PikaStdDevice_GPIO_platformHigh(PikaObj *self);
void PikaStdDevice_GPIO_platformLow(PikaObj *self);
void PikaStdDevice_GPIO_platformRead(PikaObj *self);
void PikaStdDevice_GPIO_platformSetMode(PikaObj *self);
int PikaStdDevice_GPIO_read(PikaObj *self);
void PikaStdDevice_GPIO_setId(PikaObj *self, int id);
void PikaStdDevice_GPIO_setMode(PikaObj *self, char* mode);
void PikaStdDevice_GPIO_setPin(PikaObj *self, char* pinName);
void PikaStdDevice_GPIO_setPull(PikaObj *self, char* pull);

#endif
