value = 2 ** 5 + 7 // 2
value += 3 * 4
print(value >= 45 and value != 0)
items = [3, 1, 2]
items += [4]
print(sorted(items))
print(items[1:3])
print(2 in items)
print(sum(items), min(items), max(items), len(items))
print(divmod(9, 4))
print(+3)
print(-3)
print(~3)
print(not 0)
print(5 / 2)
print(5 // 2)
print(5.0 // 2)
print(5 % 2)
print(2 ** 3)
print((-2) ** 3)
print(pow(-2, 3))
print(pow(-2, 3, 5))
print(pow(-2, 3, -5))
print(pow(2, 63, 7))
print(3 < 4, 3 <= 3, 4 > 3, 4 >= 4)
print(3 == 3, 3 != 4)
print("b" in "abc", "x" not in "abc")
print("ab" * 2)
print([1] * 2)
print(False and (1 / 0))
print(True or (1 / 0))
print(1 if True else (1 / 0))
values = range(2, 8, 2)
print(len(values))
cursor = iter(values)
print(next(cursor))
print(next(cursor))
print(next(cursor))
print(next(cursor, 99))
print(list(values[::-1]))
