/* SPEC: PJ2026-0501 V2内核 v0.43；稳定状态合同。 */
#ifndef PIKA_STATUS_H
#define PIKA_STATUS_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    PIKA_STATUS_OK = 0,
    PIKA_STATUS_INVALID_ARGUMENT = 1,
    PIKA_STATUS_UNSUPPORTED_FORMAT = 2,
    PIKA_STATUS_UNKNOWN_OPCODE = 3,
    PIKA_STATUS_INVALID_OPERAND = 4,
    PIKA_STATUS_INVALID_CONTROL_FLOW = 5,
    PIKA_STATUS_INVALID_FUNCTION = 6,
    PIKA_STATUS_STORAGE_TOO_SMALL = 7,
    PIKA_STATUS_CALL_DEPTH_EXCEEDED = 8,
    PIKA_STATUS_DIVISION_BY_ZERO = 9,
    PIKA_STATUS_INTERNAL_ERROR = 10,
    PIKA_STATUS_LEX_ERROR = 11,
    PIKA_STATUS_SYNTAX_ERROR = 12,
    PIKA_STATUS_UNSUPPORTED_SYNTAX = 13,
    PIKA_STATUS_UNDEFINED_NAME = 14,
    PIKA_STATUS_FRONTEND_LIMIT = 15,
    PIKA_STATUS_OUTPUT_ERROR = 16,
    PIKA_STATUS_IO_ERROR = 17,
    PIKA_STATUS_ARGUMENT_COUNT = 18,
    PIKA_STATUS_UNSUPPORTED_CAPABILITY = 19,
    PIKA_STATUS_CAPABILITY_DEPENDENCY = 20,
    PIKA_STATUS_MODULE_NOT_FOUND = 21,
    PIKA_STATUS_MEMBER_NOT_FOUND = 22,
    PIKA_STATUS_DUPLICATE_BINDING = 23,
    PIKA_STATUS_BINDING_SCHEMA = 24,
    PIKA_STATUS_TYPE_MISMATCH = 25,
    PIKA_STATUS_CALLBACK_ERROR = 26,
    PIKA_STATUS_MODULE_CYCLE = 27,
    PIKA_STATUS_MODULE_CONFLICT = 28,
    PIKA_STATUS_UNKNOWN_KEYWORD = 29,
    PIKA_STATUS_DUPLICATE_ARGUMENT = 30,
    PIKA_STATUS_POSITIONAL_AFTER_KEYWORD = 31,
    PIKA_STATUS_EXCEPTION = 32,
    PIKA_STATUS_RUNTIME_ERROR = 33,
    PIKA_STATUS_VALUE_ERROR = 34,
    PIKA_STATUS_TYPE_ERROR = 35,
    PIKA_STATUS_OS_ERROR = 36,
    PIKA_STATUS_SOCKET_CLOSED = 37,
    PIKA_STATUS_SOCKET_WOULD_BLOCK = 38,
    PIKA_STATUS_SOCKET_TIMEOUT = 39,
    PIKA_STATUS_SOCKET_DNS_ERROR = 40,
    PIKA_STATUS_SOCKET_CONNECTION_REFUSED = 41,
    PIKA_STATUS_SOCKET_CONNECTION_RESET = 42,
    PIKA_STATUS_SOCKET_RECEIVE_BYTE_LIMIT = 43,
    PIKA_STATUS_SOCKET_HOST_BYTE_LIMIT = 44,
    PIKA_STATUS_SOCKET_OBJECT_LIMIT = 45,
    PIKA_STATUS_OVERFLOW_ERROR = 46,
    PIKA_STATUS_ASSERTION_ERROR = 47,
} PikaStatus;

typedef enum {
    PIKA_EXCEPTION_NONE = 0,
    PIKA_EXCEPTION_EXCEPTION = 1,
    PIKA_EXCEPTION_RUNTIME_ERROR = 2,
    PIKA_EXCEPTION_VALUE_ERROR = 3,
    PIKA_EXCEPTION_TYPE_ERROR = 4,
    PIKA_EXCEPTION_ZERO_DIVISION_ERROR = 5,
    PIKA_EXCEPTION_OS_ERROR = 6,
    PIKA_EXCEPTION_ANY = 7,
    PIKA_EXCEPTION_OVERFLOW_ERROR = 8,
    PIKA_EXCEPTION_ASSERTION_ERROR = 9,
} PikaExceptionKind;

const char* pika_status_name(PikaStatus status);
int pika_status_is_known(PikaStatus status);
int pika_status_can_raise(PikaStatus status);
PikaExceptionKind pika_status_exception_kind(PikaStatus status);
const char* pika_status_exception_name(PikaStatus status);
int pika_status_matches_exception(PikaStatus status,
                                  PikaExceptionKind kind);

#ifdef __cplusplus
}
#endif

#endif
