class kvdb_t:
    ...


class FlashDB:
    FDB_KVDB_CTRL_SET_SEC_SIZE: int
    FDB_KVDB_CTRL_GET_SEC_SIZE: int
    FDB_KVDB_CTRL_SET_LOCK: int
    FDB_KVDB_CTRL_SET_UNLOCK: int
    FDB_KVDB_CTRL_SET_FILE_MODE: int
    FDB_KVDB_CTRL_SET_MAX_SIZE: int
    FDB_KVDB_CTRL_SET_NOT_FORMAT: int

    def __init__(self): ...

    # def blob_make(blob:any, value_buf:any, buf_len:int)->any:...

    # def blob_read(db:any, blob:any)->any:...

    def kvdb_init(name: str, path: str, default_kv: dict,
                  user_data: any) -> object: ...

    def kvdb_control(kvdb: any, cmd: int, arg: any) -> int: ...

    def kvdb_deinit(kvdb: any): ...

    def kv_set_blob(kvdb: object, key: str, blob: any) -> int: ...

    # def kv_set(kvdb:any, key:str, value:str)->int:...

    def kv_get_blob(kvdb: object, key: str, size: int) -> list: ...

    # def kv_get_obj(kvdb:any, key:str, kv:any)->any:...

    # def kv_get(kvdb:any, key:str)->any:...

    # def kv_del(kvdb:any, key:str)->int:...

    # def kv_set_default(kvdb:any)->int:...

    def kv_print(kvdb: object): ...

    # def kv_to_blob(kv:any, blob:any)->any:...

    # def kv_iterator_init(kvdb:any, itr:any)->any:...

    # def kv_iterate(kvdb:any, itr:any)->any:...

    def __del__(self): ...

