from typing import Any


def compare_digest(left: Any, right: Any) -> bool: ...


class HMAC:
    def __init__(
        self,
        key: Any,
        message: Any,
        digestmod: str,
    ) -> None: ...
    def update(self, message: Any) -> None: ...
    def digest(self) -> bytes: ...
    def hexdigest(self) -> str: ...
    def copy(self) -> HMAC: ...
