from typing import Any


def seed(a: int) -> None: ...
def random() -> float: ...
def randint(a: int, b: int) -> int: ...
def randrange(start: int, stop: int, step: int = 1) -> int: ...
def uniform(a: Any, b: Any) -> float: ...
