print(abs(-9))
print(all([1, 2, 3]))
print(any([0, 2]))
print(ascii("x"))
print(bin(10))
print(bool([]))
print(bytes([65, 66]))
print(bytearray([65]))
print(chr(65))
print(dict([(1, 2)]))
print(divmod(9, 4))
print(list(enumerate(["a", "b"])))
print(float(2))
print(format(12, "04d"))
print(hash(7))
print(hex(31))
value = []
print(id(value) == id(value))
print(int("12"))
print(isinstance(1, type(1)))
print(len("abc"))
print(list("ab"))
print(max(1, 5, 3))
print(min(1, 5, 3))
print(oct(9))
print(ord("A"))
print(pow(2, 3, 5))
print(1, 2)
print(list(range(1, 4)))
print(repr("x"))
print(list(reversed([1, 2, 3])))
print(round(3.25, 1))
print(set([2, 1, 2]))
print(slice(1, 5, 2))
print(sorted([3, 1, 2]))
print(str(7))
print(sum([1, 2, 3]))
print(tuple([1, 2]))
print(type(1))
print(list(zip([1, 2], ["a", "b"])))
cursor = iter([4, 5])
print(next(cursor))
print(next(cursor))
