import STM32G0
import PikaPiZero

class GPIO(STM32G0.GPIO): ...

class Time(STM32G0.Time): ...

class ADC(STM32G0.ADC): ...

class UART(STM32G0.UART): ...

class PWM(STM32G0.PWM): ...

class RGB(PikaPiZero.RGB): ...

class KEY(PikaPiZero.KEY): ...

# class LCD(PikaPiZero.LCD): ...

# class Task(STM32G0.Task): ...

# class IIC(STM32G0.IIC): ...

class Point(PikaPiZero.Point): ...
