#api
from PikaObj import *

class MemChecker(TinyObj):
    def max(self):...
    def now(self):...
    def getMax(self) -> float:...
    def getNow(self) -> float:...
    def resetMax(self):...


class SysObj(BaseObj):
    def type(self, arg: any):...
    def remove(self, argPath: str):...
    def int(self, arg: any) -> int:...
    def float(self, arg: any) -> float:...
    def str(self, arg: any) -> str:...
    def iter(self, arg: any) -> any:...
    def range(self, a1: int, a2: int) -> any:...
    def __set__(self, obj: any, key: any, val: any, obj_str: str):...
    def __get__(self, obj: any, key: any) -> any:...
    def len(self, arg:any) -> int:...
    def list(self) -> any:...
    def dict(self) -> any:...

class RangeObj(TinyObj):
    def __next__(self) -> any:...


class StringObj(TinyObj):
    def __next__(self) -> any:...

class PikaObj(TinyObj):...
