/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * https://pikadoc.readthedocs.io/zh/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef __PikaStdDevice_IIC__H
#define __PikaStdDevice_IIC__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New_PikaStdDevice_IIC(Args *args);

void PikaStdDevice_IIC___init__(PikaObj *self);
void PikaStdDevice_IIC_disable(PikaObj *self);
void PikaStdDevice_IIC_enable(PikaObj *self);
void PikaStdDevice_IIC_platformDisable(PikaObj *self);
void PikaStdDevice_IIC_platformEnable(PikaObj *self);
void PikaStdDevice_IIC_platformRead(PikaObj *self);
void PikaStdDevice_IIC_platformReadBytes(PikaObj *self);
void PikaStdDevice_IIC_platformWrite(PikaObj *self);
void PikaStdDevice_IIC_platformWriteBytes(PikaObj *self);
char* PikaStdDevice_IIC_read(PikaObj *self, int addr, int length);
Arg* PikaStdDevice_IIC_readBytes(PikaObj *self, int addr, int length);
void PikaStdDevice_IIC_setDeviceAddr(PikaObj *self, int addr);
void PikaStdDevice_IIC_setPinSCL(PikaObj *self, char* pin);
void PikaStdDevice_IIC_setPinSDA(PikaObj *self, char* pin);
void PikaStdDevice_IIC_write(PikaObj *self, int addr, char* data);
void PikaStdDevice_IIC_writeBytes(PikaObj *self, int addr, uint8_t* data, int length);

#endif
