/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * https://pikadoc.readthedocs.io/zh/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef __PikaStdDevice_ADC__H
#define __PikaStdDevice_ADC__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New_PikaStdDevice_ADC(Args *args);

void PikaStdDevice_ADC___init__(PikaObj *self);
void PikaStdDevice_ADC_disable(PikaObj *self);
void PikaStdDevice_ADC_enable(PikaObj *self);
void PikaStdDevice_ADC_platformDisable(PikaObj *self);
void PikaStdDevice_ADC_platformEnable(PikaObj *self);
void PikaStdDevice_ADC_platformRead(PikaObj *self);
pika_float PikaStdDevice_ADC_read(PikaObj *self);
void PikaStdDevice_ADC_setPin(PikaObj *self, char* pin);

#endif
