assert "1" == "%d" % (1)
assert "None" == "%s" % (None)
assert "1.0" == "%0.1f" % (1.0)
assert "1" == "%r" % (1)
assert "None" == "%r" % (None)
assert "True" == "%r" % (True)
assert "1, 2" == "%s, %s" % (1, 2)
assert "1, False" == "%s, %s" % (1, False)
print("PASS")
