/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * https://pikadoc.readthedocs.io/zh/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef __pika_lvgl_style_t__H
#define __pika_lvgl_style_t__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New_pika_lvgl_style_t(Args *args);

void pika_lvgl_style_t___init__(PikaObj *self);
void pika_lvgl_style_t_init(PikaObj *self);
void pika_lvgl_style_t_set_bg_color(PikaObj *self, PikaObj* color);
void pika_lvgl_style_t_set_bg_opa(PikaObj *self, int opa);
void pika_lvgl_style_t_set_outline_color(PikaObj *self, PikaObj* color);
void pika_lvgl_style_t_set_outline_pad(PikaObj *self, int pad);
void pika_lvgl_style_t_set_outline_width(PikaObj *self, int w);
void pika_lvgl_style_t_set_radius(PikaObj *self, int radius);
void pika_lvgl_style_t_set_shadow_color(PikaObj *self, PikaObj* color);
void pika_lvgl_style_t_set_shadow_spread(PikaObj *self, int s);
void pika_lvgl_style_t_set_shadow_width(PikaObj *self, int w);

#endif
