# SPEC: PJ2026-050110 PikaPython CLI v0.25; configurable boot entry.
import ast
import hashlib
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

from .errors import PackageError


GENERATED_SCHEMA = "pika.generated-sources/v1"
PROGRAM_IMAGE_MANIFEST_SCHEMA = "pika.program-image/modules/2"


def _cli_tools():
    return Path(__file__).with_name("tools")


def read_json(path, code):
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError) as error:
        raise PackageError(code, "cannot read %s: %s" % (path, error)) from error


def _run_tool(command, cwd, code, preserve_json_error=False):
    try:
        result = subprocess.run(
            command,
            cwd=cwd,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            check=False,
        )
    except OSError as error:
        raise PackageError(
            code,
            "cannot start prebuild tool: %s" % error,
            stage="prebuild",
        ) from error
    if result.returncode != 0:
        if preserve_json_error:
            try:
                payload = json.loads(result.stdout)
            except json.JSONDecodeError:
                payload = None
            if (
                isinstance(payload, dict)
                and payload.get("ok") is False
                and isinstance(payload.get("code"), str)
                and isinstance(payload.get("error"), str)
            ):
                message = payload["error"]
                bound = payload.get("bound")
                configured = payload.get("configured")
                observed = payload.get("observed")
                if (
                    isinstance(bound, str)
                    and bound
                    and isinstance(configured, int)
                    and not isinstance(configured, bool)
                    and isinstance(observed, int)
                    and not isinstance(observed, bool)
                ):
                    message += ": %s configured=%d observed=%d" % (
                        bound,
                        configured,
                        observed,
                    )
                line = payload.get("line")
                column = payload.get("column")
                if (
                    isinstance(line, int)
                    and not isinstance(line, bool)
                    and line > 0
                    and isinstance(column, int)
                    and not isinstance(column, bool)
                    and column > 0
                ):
                    message += " at line %d column %d" % (
                        line,
                        column,
                    )
                raise PackageError(
                    payload["code"],
                    message,
                    stage=payload.get("stage", "prebuild"),
                    module=payload.get("module"),
                )
        detail = (result.stderr or result.stdout).strip()
        raise PackageError(
            code,
            detail[-4000:] or "%s failed" % code,
            stage="prebuild",
        )


def _empty_capability(stage):
    header = "\n".join([
        "/* Generated by pikapython-cli. Do not edit. */",
        "#ifndef PIKA_CAPABILITY_CONFIG_H",
        "#define PIKA_CAPABILITY_CONFIG_H",
        "#endif",
        "",
    ])
    manifest = {
        "schema": "pika.capability-prebuild/v1",
        "profile": None,
        "closure": [],
        "macros": {},
        "pythonModules": [],
        "resourceLimits": {},
    }
    (stage / "pika_capability_config.h").write_text(header, encoding="ascii")
    (stage / "capability-config.h").write_text(header, encoding="ascii")
    (stage / "pika_capability_manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n",
        encoding="ascii",
    )
    return manifest


def _generate_capability(stage, project, source, config):
    capability = config.get("capability")
    if capability is None:
        return _empty_capability(stage)
    config_file = (project / capability["configFile"]).resolve()
    tool = _cli_tools() / "capability-prebuild-cli.py"
    if not config_file.is_file() or not tool.is_file():
        raise PackageError(
            "capability_input_missing",
            "capability config or prebuild tool is missing",
            stage="prebuild",
        )
    output = stage.parent / "capability"
    _run_tool(
        [
            sys.executable,
            str(tool),
            "--config",
            str(config_file),
            "--profile",
            capability["profile"],
            "--output",
            str(output),
        ],
        project,
        "capability_prebuild_failed",
        preserve_json_error=True,
    )
    for path in sorted(output.iterdir(), key=lambda item: item.name):
        if path.is_file():
            shutil.copy2(path, stage / path.name)
    shutil.copy2(
        stage / "pika_capability_config.h", stage / "capability-config.h"
    )
    return read_json(
        stage / "pika_capability_manifest.json",
        "capability_manifest_invalid",
    )


def _generate_bindings(stage, source, install, capabilities):
    descriptors = []
    public = [path for path in install["files"] if "/" not in path]
    for target in sorted(path for path in public if path.endswith(".pyi")):
        if not capabilities:
            raise PackageError(
                "capability_required",
                "binding prebuild requires an explicit capability profile",
                stage="prebuild",
            )
        module = target[:-4]
        origin = install["fileOrigins"].get(target)
        input_path = source / origin if origin else None
        tool = _cli_tools() / "binding-prebuild-cli.py"
        if input_path is None or not input_path.is_file() or not tool.is_file():
            raise PackageError(
                "binding_input_missing",
                "binding source or prebuild tool is missing: %s" % target,
                stage="prebuild",
            )
        output = stage.parent / ("binding-" + module)
        command = [
            sys.executable,
            str(tool),
            "prebuild",
            "--module",
            module,
            "--input",
            str(input_path),
            "--output",
            str(output),
        ]
        for capability in capabilities:
            command.extend(["--capability", capability])
        _run_tool(command, source, "binding_prebuild_failed")
        descriptor_path = output / (module + ".json")
        descriptors.append(
            read_json(descriptor_path, "binding_descriptor_invalid")
        )
        for suffix in ("_binding.c", "_binding.h"):
            shutil.copy2(output / (module + suffix), stage / (module + suffix))
    collection = {
        "schema": "pika.binding-collection/v1",
        "modules": descriptors,
    }
    (stage / "binding-descriptor.json").write_text(
        json.dumps(collection, indent=2, sort_keys=True) + "\n",
        encoding="ascii",
    )
    return descriptors


def _active_install(install, capability):
    closure = set(capability.get("closure", []))
    known = set(capability.get("macros", {}))
    disabled = set()
    for package in install["packages"]:
        selected = package.get("capability")
        if selected is None:
            continue
        if selected not in known:
            raise PackageError(
                "package_capability_unknown",
                "installed package requires an unknown capability: %s"
                % selected,
                stage="prebuild",
            )
        if selected not in closure:
            disabled.add(package["name"])
    owners = install.get("filePackages", {})
    active_files = [
        path
        for path in install["files"]
        if owners.get(path) not in disabled
    ]
    active = dict(install)
    active["files"] = active_files
    active["fileOrigins"] = {
        path: install["fileOrigins"][path] for path in active_files
    }
    active["filePackages"] = {
        path: owners[path] for path in active_files if path in owners
    }
    return active


def _render_bytes(data):
    if not data:
        return "    0x00u,"
    lines = []
    for offset in range(0, len(data), 12):
        values = ", ".join(
            "0x%02xu" % item for item in data[offset : offset + 12]
        )
        lines.append("    %s," % values)
    return "\n".join(lines)


def _python_imports(name, path, data):
    try:
        tree = ast.parse(data, filename=path.name)
    except (SyntaxError, ValueError) as error:
        raise PackageError(
            "python_module_scan_failed",
            "cannot scan Python imports in %s: %s" % (path.name, error),
            stage="module-discovery",
            module=name,
        ) from error
    imports = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            imports.update(alias.name for alias in node.names)
        elif (
            isinstance(node, ast.ImportFrom)
            and node.level == 0
            and node.module is not None
        ):
            imports.add(node.module)
    return sorted(imports)


def _python_modules(project, install, config):
    boot_name = config.get("bootEntry", "main.py")
    boot_entry = project / boot_name
    if not boot_entry.is_file():
        raise PackageError(
            "boot_entry_missing",
            "configured bootEntry is missing: %s" % boot_name,
            stage="prebuild",
        )
    installed_names = {
        path[:-3]
        for path in install["files"]
        if "/" not in path and path.endswith(".py")
    }
    paths = sorted(project.glob("*.py"), key=lambda item: item.name)
    if boot_entry not in paths:
        paths.append(boot_entry)
    discovered = []
    modules = []
    names = set()
    sources = {}
    source_paths = {}
    for path in sorted(paths, key=lambda item: item.name):
        name = "__main__" if path == boot_entry else path.stem
        if name in names:
            raise PackageError(
                "module_name_conflict",
                "multiple Python sources map to module: %s" % name,
                stage="prebuild",
            )
        names.add(name)
        data = path.read_bytes()
        discovered.append((name, data))
        sources[name] = data
        source_paths[name] = path
        modules.append({
            "name": name,
            "path": path.relative_to(project).as_posix(),
            "sha256": hashlib.sha256(data).hexdigest(),
        })
    policy = config.get("pythonModules")
    if policy is None:
        root_names = set(installed_names)
        module_format = "source"
    else:
        include = policy["include"]
        available = {
            name for name, _ in discovered if name != "__main__"
        }
        if include == ["*"]:
            root_names = set(installed_names)
        else:
            root_names = set(include)
            missing = sorted(root_names.difference(available))
            if missing:
                raise PackageError(
                    "python_module_not_found",
                    "selected Python module is not available: %s"
                    % missing[0],
                    stage="module-discovery",
                    module=missing[0],
                )
        module_format = policy["format"]
    root_names.add("__main__")
    selected_names = set()
    pending = sorted(root_names)
    while pending:
        name = pending.pop(0)
        if name in selected_names:
            continue
        selected_names.add(name)
        for imported in _python_imports(
            name, source_paths[name], sources[name]
        ):
            if imported in sources and imported not in selected_names:
                pending.append(imported)
        pending.sort()
    selected = [
        (name, data)
        for name, data in discovered
        if name in selected_names
    ]
    selected_metadata = [
        item for item in modules if item["name"] in selected_names
    ]
    skipped = [
        {"name": item["name"], "reason": "not-selected"}
        for item in modules
        if item["name"] not in selected_names
    ]
    return selected, selected_metadata, module_format, skipped


def _digest_json(value):
    data = json.dumps(
        value, ensure_ascii=True, sort_keys=True, separators=(",", ":")
    ).encode("ascii")
    return hashlib.sha256(data).hexdigest()


def _program_format_version(source):
    header = source / "pikapython-kernel" / "pika_ir.h"
    match = None
    try:
        for line in header.read_text(encoding="ascii").splitlines():
            if line.startswith("#define PIKA_PROGRAM_FORMAT_VERSION "):
                match = line.split()[2].rstrip("uU")
                break
    except (OSError, UnicodeError, IndexError, ValueError) as error:
        raise PackageError(
            "program_format_version_invalid",
            "cannot read the Program Image format version: %s" % error,
            stage="manifest",
        ) from error
    if match is None or not match.isdigit():
        raise PackageError(
            "program_format_version_invalid",
            "PIKA_PROGRAM_FORMAT_VERSION is missing",
            stage="manifest",
        )
    return int(match)


def _callback_name(module, class_name, function):
    name = function
    if function == "__init__":
        name = "init"
    elif class_name is not None and function == "init":
        name = "method_init"
    parts = ["pika", "binding", module]
    if class_name is not None:
        parts.append(class_name)
    parts.append(name)
    return "_".join(parts)


def _generate_host_callbacks(path, bindings):
    lines = [
        "#include <stddef.h>",
        "",
        '#include "pika_binding.h"',
    ]
    for binding in bindings:
        lines.append(
            '#include "%s_binding.h"' % binding["module"]
        )
    lines.append("")
    for binding in bindings:
        module = binding["module"]
        callables = [
            (None, function)
            for function in binding["functions"]
        ]
        for binding_class in binding["classes"]:
            callables.append(
                (binding_class["name"], binding_class["constructor"])
            )
            callables.extend(
                (binding_class["name"], method)
                for method in binding_class["methods"]
            )
        for class_name, function in callables:
            symbol = _callback_name(
                module, class_name, function["name"]
            )
            lines.extend([
                "PikaStatus %s(" % symbol,
                "    const PikaBindingCall* call,",
                "    PikaBindingValue* result) {",
                "    (void)call;",
                "    if (result != NULL) {",
                "        result->kind = PIKA_BINDING_VALUE_NONE;",
                "        result->as.integer = 0;",
                "    }",
                "    return PIKA_STATUS_OK;",
                "}",
                "",
            ])
        for binding_class in binding["classes"]:
            symbol = "pika_binding_%s_%s_destroy" % (
                module, binding_class["name"]
            )
            lines.extend([
                "void %s(void* context, void* instance) {" % symbol,
                "    (void)context;",
                "    (void)instance;",
                "}",
                "",
            ])
    path.write_text("\n".join(lines), encoding="ascii")


def _generate_host_input(
    path, sources, public_names, bindings, configuration_digest,
    capability_digest
):
    lines = [
        "#include <stddef.h>",
        "#include <stdint.h>",
        "#include <stdio.h>",
        "#include <string.h>",
        "",
        '#include "pika_frontend.h"',
        '#include "program-prebuild.h"',
    ]
    for binding in bindings:
        lines.append(
            '#include "%s_binding.h"' % binding["module"]
        )
    lines.extend([
        "",
        "typedef struct {",
        "    const char* name;",
        "    const uint8_t* data;",
        "    size_t size;",
        "} PikaHostModule;",
        "",
    ])
    entries = []
    module_names = []
    source_identities = []
    for index, (name, data) in enumerate(sources):
        symbol = "pika_host_module_%d" % index
        digest_symbol = "pika_host_module_%d_digest" % index
        lines.extend([
            "static const uint8_t %s[] = {" % symbol,
            _render_bytes(data),
            "};",
            "static const uint8_t %s[] = {" % digest_symbol,
            _render_bytes(hashlib.sha256(data).digest()),
            "};",
            "",
        ])
        entries.append(
            '    {"%s", %s, %du},' % (name, symbol, len(data))
        )
        source_identities.append(
            '    {"%s", %s, 32u},' % (name, digest_symbol)
        )
    module_names = [
        '    "%s",' % name for name in sorted(public_names)
    ]
    lines.extend([
        "static const PikaHostModule pika_host_modules[] = {",
        *entries,
        "};",
    ])
    if module_names:
        lines.extend([
            "static const char* const pika_host_module_names[] = {",
            *module_names,
            "};",
            "static const size_t pika_host_module_name_count = %du;"
            % len(module_names),
        ])
    else:
        lines.extend([
            "static const char* const* pika_host_module_names = NULL;",
            "static const size_t pika_host_module_name_count = 0u;",
        ])
    lines.extend([
        "static const PikaProgramImageSourceIdentity "
        "pika_host_source_identities[] = {",
        *source_identities,
        "};",
        "static const uint8_t pika_host_configuration_digest[] = {",
        _render_bytes(configuration_digest),
        "};",
        "static const uint8_t pika_host_capability_digest[] = {",
        _render_bytes(capability_digest),
        "};",
        "static const PikaProgramImageExportIdentity "
        "pika_host_export_identity = {",
        "    pika_host_source_identities,",
        "    %du," % len(sources),
        "    pika_host_configuration_digest,",
        "    32u,",
        "    pika_host_capability_digest,",
        "    32u,",
        "};",
        "",
        "static PikaStatus pika_host_load(",
        "    void* context,",
        "    const char* name,",
        "    const char** source,",
        "    size_t* length) {",
        "    size_t index;",
        "    (void)context;",
        "    if (name == NULL || source == NULL || length == NULL) {",
        "        return PIKA_STATUS_INVALID_ARGUMENT;",
        "    }",
        "    for (index = 0u;",
        "         index < sizeof(pika_host_modules) /",
        "                     sizeof(pika_host_modules[0]);",
        "         ++index) {",
        "        if (strcmp(pika_host_modules[index].name, name) == 0) {",
        "            *source = (const char*)pika_host_modules[index].data;",
        "            *length = pika_host_modules[index].size;",
        "            return PIKA_STATUS_OK;",
        "        }",
        "    }",
        "    return PIKA_STATUS_MODULE_NOT_FOUND;",
        "}",
        "",
        "static void pika_host_release(void* context, const char* source) {",
        "    (void)context;",
        "    (void)source;",
        "}",
        "",
        "static void pika_host_report_error(",
        "    PikaStatus status,",
        "    const char* stage,",
        "    const PikaDiagnostic* diagnostic) {",
        "    const char* module = diagnostic == NULL",
        '        ? "" : diagnostic->source_name;',
        "    unsigned line = diagnostic == NULL ? 0u : diagnostic->line;",
        "    unsigned column = diagnostic == NULL ? 0u : diagnostic->column;",
        "    unsigned offset = diagnostic == NULL ? 0u : diagnostic->offset;",
        "    const char* reason = diagnostic == NULL",
        '        ? "" : pika_frontend_diagnostic_reason_name(diagnostic->reason);',
        "    const char* bound = diagnostic == NULL",
        '        ? "" : pika_frontend_bound_macro(diagnostic->bound);',
        "    unsigned configured = diagnostic == NULL",
        "        ? 0u : diagnostic->configured;",
        "    unsigned observed = diagnostic == NULL",
        "        ? 0u : diagnostic->observed;",
        '    printf("{\\"ok\\":false,\\"code\\":\\"%s\\",",',
        "           pika_status_name(status));",
        '    printf("\\"error\\":\\"%s\\",\\"stage\\":\\"%s\\",",',
        "           pika_status_name(status), stage);",
        "    if (module[0] == '\\0') {",
        '        fputs("\\"module\\":null,", stdout);',
        "    } else {",
        '        printf("\\"module\\":\\"%s\\",", module);',
        "    }",
        '    printf("\\"line\\":%u,\\"column\\":%u,\\"offset\\":%u,"',
        '           "\\"reason\\":\\"%s\\",\\"bound\\":\\"%s\\","',
        '           "\\"configured\\":%u,\\"observed\\":%u}\\n",',
        "           line, column, offset, reason, bound, configured, observed);",
        "}",
        "",
    ])
    if bindings:
        lines.extend([
            "static const PikaBindingModule* pika_host_bindings[%du];"
            % len(bindings),
            "",
        ])
    lines.extend([
        "int main(int argc, char** argv) {",
        "    PikaModuleProvider provider = {",
        "        pika_host_load, pika_host_release, NULL",
        "    };",
        "    PikaFrontendConfig config;",
        "    PikaCompiledModule* module = NULL;",
        "    PikaDiagnostic diagnostic = {0};",
        "    PikaStatus status;",
        "    if (argc != 4) {",
        '        fputs("usage: program-prebuild <source> <header> "',
        '              "<metadata>\\n",',
        "              stderr);",
        "        return 2;",
        "    }",
    ])
    if bindings:
        lines.extend([
            "    PikaBindingRegistry registry;",
            "    status = pika_binding_registry_initialize(",
            "        &registry, pika_host_bindings, %du);" % len(bindings),
            "    if (status != PIKA_STATUS_OK) return 3;",
        ])
    for index, binding in enumerate(bindings):
        lines.extend([
            "    pika_host_bindings[%du] = "
            "pika_binding_module_%s();"
            % (index, binding["module"]),
            "    status = pika_binding_registry_register(",
            "        &registry, pika_host_bindings[%du]);" % index,
            "    if (status != PIKA_STATUS_OK) return 4;",
        ])
    if bindings:
        lines.extend([
            "    config.enabled = PIKA_CAPABILITY_BINDING_DEFAULT |",
            "                     (PIKA_CAPABILITY_OBJECT_CLASS &",
            "                      PIKA_CAPABILITY_PROVIDED);",
            "#if PIKA_REPL_ENABLE",
            "    config.enabled |= PIKA_CAPABILITY_NAME_GLOBAL &",
            "                      PIKA_CAPABILITY_PROVIDED;",
            "#endif",
            "    config.bindings = &registry;",
        ])
    else:
        lines.extend([
            "    config.enabled = PIKA_CAPABILITY_APPLICATION_DEFAULT |",
            "                     (PIKA_CAPABILITY_OBJECT_CLASS &",
            "                      PIKA_CAPABILITY_PROVIDED);",
            "#if PIKA_REPL_ENABLE",
            "    config.enabled |= PIKA_CAPABILITY_NAME_GLOBAL &",
            "                      PIKA_CAPABILITY_PROVIDED;",
            "#endif",
            "    config.bindings = NULL;",
        ])
    lines.extend([
        "    status = pika_module_graph_compile_image(",
        '        "__main__", pika_host_module_names,',
        "        pika_host_module_name_count,",
        "        &provider, &config, &module, &diagnostic);",
        "    if (status != PIKA_STATUS_OK) {",
        '        pika_host_report_error(status, "module-compile",',
        "                               &diagnostic);",
        "        return 5;",
        "    }",
        "    status = pika_program_image_export(",
        "        module, argv[1], argv[2], argv[3],",
        '        "pika_python_program_image",',
        "        &pika_host_export_identity);",
        "    pika_compiled_module_destroy(module);",
        "    if (status != PIKA_STATUS_OK) {",
        '        pika_host_report_error(status, "image-export", NULL);',
        "        return 6;",
        "    }",
        "    return 0;",
        "}",
        "",
    ])
    path.write_text("\n".join(lines), encoding="ascii")


def _host_source_files(source):
    manifest = read_json(
        _cli_tools() / "source-manifest.json",
        "program_source_manifest_invalid",
    )
    groups = manifest.get("groups")
    if (
        manifest.get("schema") != "pika.source-manifest/v1"
        or not isinstance(groups, dict)
    ):
        raise PackageError(
            "program_source_manifest_invalid",
            "host compiler source manifest is unsupported",
            stage="prebuild",
        )
    files = []
    for group in ("runtime", "frontend"):
        values = groups.get(group)
        if not isinstance(values, list) or not values:
            raise PackageError(
                "program_source_manifest_invalid",
                "host compiler source group is missing: %s" % group,
                stage="prebuild",
            )
        for value in values:
            source_path = source / value
            if not source_path.is_file():
                raise PackageError(
                    "program_source_missing",
                    "host compiler source is missing: %s" % value,
                    stage="prebuild",
                )
            files.append(source_path)
    return files


def _compile_program(
    stage,
    source,
    sources,
    public_names,
    bindings,
    configuration_digest,
    capability_digest,
    publish_image,
):
    compiler_name = os.environ.get("CC", "cc")
    compiler = shutil.which(compiler_name)
    if compiler is None:
        raise PackageError(
            "host_compiler_not_found",
            "host C compiler was not found: %s" % compiler_name,
            'Install a host C compiler or set "CC".',
            stage="prebuild",
        )
    host = stage.parent / "program-host"
    host.mkdir()
    input_source = host / "program-input.c"
    callbacks = host / "program-callbacks.c"
    executable = host / "program-prebuild"
    metadata = host / "frontend-metadata.json"
    _generate_host_input(
        input_source,
        sources,
        public_names,
        bindings,
        bytes.fromhex(configuration_digest),
        bytes.fromhex(capability_digest),
    )
    _generate_host_callbacks(callbacks, bindings)
    exporter = source / "pikapython-kernel" / "program-prebuild.c"
    exporter_header = source / "pikapython-kernel" / "program-prebuild.h"
    if not exporter.is_file() or not exporter_header.is_file():
        raise PackageError(
            "program_prebuild_tool_missing",
            "host program prebuild tool is missing",
            stage="prebuild",
        )
    command = [
        compiler,
        "-std=c99",
        "-pedantic-errors",
        "-O2",
        "-I",
        str(stage),
        "-I",
        str(source / "pikapython-kernel"),
        "-I",
        str(_cli_tools()),
    ]
    command.extend(str(path) for path in _host_source_files(source))
    command.extend([
        str(exporter),
        str(input_source),
        str(callbacks),
    ])
    command.extend(
        str(stage / ("%s_binding.c" % binding["module"]))
        for binding in bindings
    )
    command.extend(["-lm", "-o", str(executable)])
    _run_tool(command, source, "program_host_compile_failed")
    output_directory = stage if publish_image else host
    _run_tool(
        [
            str(executable),
            str(output_directory / "pikapython_program.c"),
            str(output_directory / "pikapython_program.h"),
            str(metadata),
        ],
        source,
        "program_prebuild_failed",
        preserve_json_error=True,
    )
    value = read_json(metadata, "program_frontend_metadata_invalid")
    if (
        value.get("schema")
        != "pika.program-image/frontend-metadata-v1"
        or value.get("entryModule") != "__main__"
        or not isinstance(value.get("modules"), list)
    ):
        raise PackageError(
            "program_frontend_metadata_invalid",
            "host frontend metadata is unsupported",
            stage="manifest",
        )
    return value


def _frontend_module_metadata(frontend_metadata, sources, public_names):
    frontend_modules = {}
    for frontend_module in frontend_metadata["modules"]:
        if not isinstance(frontend_module, dict):
            raise PackageError(
                "program_frontend_metadata_invalid",
                "host frontend module metadata must be an object",
                stage="manifest",
            )
        name = frontend_module.get("name")
        entry_function = frontend_module.get("entryFunction")
        fields = (
            "dependencies",
            "pythonImportRelocations",
            "bindingRelocations",
        )
        if (
            not isinstance(name, str)
            or not name
            or name in frontend_modules
            or not isinstance(entry_function, int)
            or isinstance(entry_function, bool)
            or entry_function < 0
            or any(
                not isinstance(frontend_module.get(field), list)
                or any(
                    not isinstance(value, str) or not value
                    for value in frontend_module[field]
                )
                or len(set(frontend_module[field]))
                != len(frontend_module[field])
                for field in fields
            )
        ):
            raise PackageError(
                "program_frontend_metadata_invalid",
                "host frontend module metadata is invalid",
                stage="manifest",
                module=name if isinstance(name, str) else None,
            )
        frontend_modules[name] = frontend_module
    candidate_names = {name for name, _ in sources}
    required_names = {"__main__", *public_names}
    actual_names = set(frontend_modules)
    if not required_names.issubset(actual_names) or not actual_names.issubset(
        candidate_names
    ):
        missing = sorted(required_names.difference(actual_names))
        extra = sorted(actual_names.difference(candidate_names))
        failed_module = (missing or extra or [None])[0]
        raise PackageError(
            "program_frontend_metadata_invalid",
            "host frontend module set does not match selected modules",
            stage="manifest",
            module=failed_module,
        )
    return frontend_modules


def _generate_python_data(
    stage, project, source, config, install, bindings, capability
):
    sources, modules, module_format, skipped = _python_modules(
        project, install, config
    )
    public_names = {
        name for name, _ in sources if name != "__main__"
    }
    selected_names = {name for name, _ in sources}
    for filename in capability.get("pythonModules", []):
        path = stage / filename
        name = Path(filename).stem
        if (
            Path(filename).name != filename
            or path.suffix != ".py"
            or not path.is_file()
            or name in selected_names
        ):
            raise PackageError(
                "capability_python_module_invalid",
                "capability Python module is invalid: %s" % filename,
                stage="prebuild",
                module=name,
            )
        data = path.read_bytes()
        sources.append((name, data))
        modules.append({
            "name": name,
            "path": filename,
            "sha256": hashlib.sha256(data).hexdigest(),
        })
        public_names.add(name)
        selected_names.add(name)
    sources.sort(key=lambda item: item[0])
    modules.sort(key=lambda item: item["name"])
    configuration_digest = _digest_json(config)
    capability_digest = _digest_json(capability)
    if module_format == "program":
        frontend_modules = _frontend_module_metadata(
            _compile_program(
                stage,
                source,
                sources,
                public_names,
                bindings,
                configuration_digest,
                capability_digest,
                True,
            ),
            sources,
            public_names,
        )
        sources = [
            item for item in sources if item[0] in frontend_modules
        ]
        modules = [
            item for item in modules
            if item["name"] in frontend_modules
        ]
    else:
        frontend_modules = {
            name: {
                "entryFunction": None,
                "dependencies": [],
                "pythonImportRelocations": [],
                "bindingRelocations": [],
            }
            for name, _ in sources
        }
    source_lines = ['#include "pikapython_modules.h"']
    if module_format == "program":
        source_lines.append('#include "pikapython_program.h"')
    for binding in bindings:
        source_lines.append(
            '#include "%s_binding.h"' % binding["module"]
        )
    source_digest_symbols = {}
    for index, (name, data) in enumerate(sources):
        symbol = "pika_python_module_%d_source_digest" % index
        source_digest_symbols[name] = symbol
        source_lines.extend([
            "",
            "static const uint8_t %s[] = {" % symbol,
            _render_bytes(hashlib.sha256(data).digest()),
            "};",
        ])
    source_lines.extend([
        "",
        "static const uint8_t pika_python_configuration_digest[] = {",
        _render_bytes(bytes.fromhex(configuration_digest)),
        "};",
        "static const uint8_t pika_python_capability_digest[] = {",
        _render_bytes(bytes.fromhex(capability_digest)),
        "};",
    ])
    source_entries = []
    for index, (name, data) in enumerate(sources):
        if module_format == "source":
            symbol = "pika_python_source_module_%d" % index
            source_lines.extend([
                "",
                "static const uint8_t %s[] = {" % symbol,
                _render_bytes(data),
                "};",
            ])
            data_expression = symbol
            size_expression = "%du" % len(data)
            format_expression = "PIKA_FROZEN_MODULE_SOURCE"
        else:
            data_expression = (
                "(const uint8_t*)&pika_python_program_image"
            )
            size_expression = "sizeof(pika_python_program_image)"
            format_expression = "PIKA_FROZEN_MODULE_PROGRAM"
        source_entries.extend([
            "    {",
            '        "%s",' % name,
            "        %s," % data_expression,
            "        %s," % size_expression,
            "        %s," % format_expression,
            "        %s," % source_digest_symbols[name],
            "        32u,",
            "    },",
        ])
    source_lines.extend([
        "",
        "const PikaFrozenModule pika_python_frozen_modules[] = {",
        *source_entries,
        "};",
        "const size_t pika_python_frozen_module_count = %du;"
        % len(sources),
        "",
    ])
    if bindings:
        source_lines.extend([
            "static const PikaBindingModule* pika_python_binding_modules[%du];"
            % len(bindings),
            "",
        ])
    source_lines.extend([
        "static PikaApplicationDescriptor pika_python_application = {",
        "    PIKA_APPLICATION_SCHEMA_VERSION,",
        "    pika_python_frozen_modules,",
        "    %du," % len(sources),
        "    NULL,",
        "    %du," % len(bindings),
        "    pika_python_configuration_digest,",
        "    32u,",
        "    pika_python_capability_digest,",
        "    32u,",
        "};",
        "",
        "PikaStatus pikaPythonInit(void) {",
    ])
    for index, binding in enumerate(bindings):
        source_lines.append(
            "    pika_python_binding_modules[%du] = "
            "pika_binding_module_%s();"
            % (index, binding["module"])
        )
    if bindings:
        source_lines.append(
            "    pika_python_application.binding_modules = "
            "pika_python_binding_modules;"
        )
    source_lines.extend([
        "    return pika_application_start(&pika_python_application);",
        "}",
        "",
        "#if PIKA_REPL_ENABLE",
        "PikaStatus pikaPythonRepl(void) {",
        "    return pika_application_repl();",
        "}",
        "#endif",
        "",
    ])
    header = "\n".join([
        "/* Generated by pikapython-cli. Do not edit. */",
        "#ifndef PIKAPYTHON_MODULES_H",
        "#define PIKAPYTHON_MODULES_H",
        "#include <stddef.h>",
        '#include "pika_application.h"',
        "extern const PikaFrozenModule pika_python_frozen_modules[];",
        "extern const size_t pika_python_frozen_module_count;",
        "PikaStatus pikaPythonInit(void);",
        "#if PIKA_REPL_ENABLE",
        "PikaStatus pikaPythonRepl(void);",
        "#endif",
        "#endif",
        "",
    ])
    (stage / "pikapython_modules.h").write_text(
        header, encoding="ascii"
    )
    (stage / "pikapython_modules.c").write_text(
        "\n".join(source_lines), encoding="ascii"
    )
    program_version = _program_format_version(source)
    manifest_modules = []
    for module in modules:
        frontend_module = frontend_modules[module["name"]]
        module_entry = dict(module)
        module_entry.update({
            "format": module_format,
            "programFormatVersion": (
                program_version if module_format == "program" else None
            ),
            "entryFunction": frontend_module["entryFunction"],
            "dependencies": frontend_module["dependencies"],
            "pythonImportRelocations":
                frontend_module["pythonImportRelocations"],
            "bindingRelocations":
                frontend_module["bindingRelocations"],
            "generatedFiles": [
                "pikapython_modules.c",
                "pikapython_modules.h",
            ] + (
                ["pikapython_program.c", "pikapython_program.h"]
                if module_format == "program"
                else []
            ),
        })
        manifest_modules.append(module_entry)
    manifest = {
        "schema": PROGRAM_IMAGE_MANIFEST_SCHEMA,
        "entryModule": "__main__",
        "configurationDigest": configuration_digest,
        "capabilityDigest": capability_digest,
        "modules": manifest_modules,
        "skippedModules": skipped,
    }
    (stage / "program-image.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n",
        encoding="ascii",
    )
    return manifest_modules, skipped


def _write_source_manifest(stage, install, modules, bindings):
    sources = sorted(
        path for path in install["files"] if path.endswith(".c")
    )
    sources.extend(sorted(path.name for path in stage.glob("*.c")))
    include_directories = {
        path.rsplit("/", 1)[0]
        for path in install["files"]
        if path.endswith(".h") and "/" in path
    }
    include_directories.add("pikapython-generated")
    value = {
        "schema": GENERATED_SCHEMA,
        "sources": sources,
        "includeDirectories": sorted(include_directories),
        "pythonModules": modules,
        "bindingModules": [item["module"] for item in bindings],
    }
    (stage / "source-manifest.json").write_text(
        json.dumps(value, indent=2, sort_keys=True) + "\n",
        encoding="ascii",
    )


def generate(stage, project, source, config, install):
    capability = _generate_capability(stage, project, source, config)
    if capability.get("profile") is None:
        raise PackageError(
            "capability_required",
            "Python program prebuild requires an explicit capability profile",
            'Use "pikapython-cli config capability" before build.',
            stage="prebuild",
        )
    active_install = _active_install(install, capability)
    bindings = _generate_bindings(
        stage, source, active_install, capability.get("closure", [])
    )
    modules, skipped = _generate_python_data(
        stage, project, source, config, active_install, bindings, capability
    )
    _write_source_manifest(stage, active_install, modules, bindings)
    program_count = sum(
        item["format"] == "program" for item in modules
    )
    source_count = sum(item["format"] == "source" for item in modules)
    return {
        "programModuleCount": program_count,
        "sourceModuleCount": source_count,
        "skippedModuleCount": len(skipped),
        "skippedModules": skipped,
    }


def publish(stage, output):
    backup = stage.parent / "previous"
    moved = False
    try:
        if output.exists():
            if output.is_symlink() or not output.is_dir():
                raise PackageError(
                    "invalid_output",
                    "generated output must be a directory",
                    stage="prebuild",
                )
            os.replace(output, backup)
            moved = True
        os.replace(stage, output)
    except Exception:
        if moved and backup.exists() and not output.exists():
            os.replace(backup, output)
        raise
    if backup.exists():
        shutil.rmtree(backup)
