#define PIKA_STACK_BUFF_SIZE 1024 * 4
#define PIKA_ASSERT_ENABLE 1
#define PIKA_MATH_ENABLE 1
#define PIKA_ARG_CACHE_ENABLE 1
#define PIKA_READ_FILE_BUFF_SIZE 1024 * 40
#define PIKA_INSTRUCT_HOOK_ENABLE 1
#define PIKA_INSTRUCT_HOOK_PERIOD 1