import native_math as native_alias
from native_math import ANSWER, Counter, add


print(add(right=22, left=20))
counter = Counter()
print(counter.increment(amount=Counter.STEP))
print(ANSWER)
print(native_alias.ANSWER)
print(native_alias.Counter.STEP)
print(0x4C + 0b10 + 0o1 + 1_000)
print(native_alias.invert(False))
print(native_alias.scale(1.25))
print(native_alias.echo("edge"))
print(native_alias.copy(b"\x00\xff"))
print(native_alias.passthrough(None))
print(native_alias.passthrough(True))
print(native_alias.passthrough(-7))
print(native_alias.passthrough(2.5))
print(native_alias.passthrough("text"))
print(native_alias.passthrough(b"bytes"))
print(native_alias.passthrough(bytearray(b"data")))
print(native_alias.nothing())
Counter = Counter()
print(Counter.increment(amount=5))
