from typing import Any


class Hash:
    def __init__(self, name: str, data: Any) -> None: ...
    def update(self, data: Any) -> None: ...
    def digest(self) -> bytes: ...
    def hexdigest(self) -> str: ...
    def copy(self) -> Hash: ...
