class AES:
    MODE_ECB: int
    MODE_CBC: int
    def __init__(self): ...
    def new(self, password:any, mode:int, iv:any): ...
    def encrypt(self, msg:any) -> any: ...
    def decrypt(self, msg:any) -> any: ...
