class Hash:
    def new(self, mode: str): ...
    def md5(self, data: any): ...
    def sha1(self, data: any): ...
    def sha224(self, data: any): ...
    def sha256(self, data: any): ...
    def sha384(self, data: any): ...
    def sha512(self, data: any): ...
    def update(self, data: any): ...
    def digest(self) -> any: ...
    def hexdigest(self) -> str: ...
    def copy(self): ...
