
class WLAN:
    def __init__(self, interface_id:int):...

    def active(self, is_active:int):...

    def checkActive(self) -> int:...

    def connect(self, ssid:str, key:str):...
    
    def connectWIthBssid(self, ssid:str, key:str, bssid:str):...

    def disconnect(self):...

    def status(self) -> int:...

    def statusWithParam(self, param:str) -> int:...

    def isconnected(self) -> int:...

    def config(self, **kwargs):...

    def checkConfig(self, param:str) -> any:...

    def ifconfig(self, config:tuple):...

    def checkIfconfig(self) -> tuple:...
