class Response:
    content_length: int
    text: str
    state_code: int
    headers: str
    url: str
    url_address: int
    session_address: int

    def json(self) -> dict: ...

    def request(self,
                method: str,
                url: str,
                timeout: float,
                data: str) -> int: ...

    def request_init(self, method: str) -> int: ...
    def request_del(self) -> None: ...
    def proto_write(self, proto: str) -> int: ...
    def urlencode_write(self, s1: str, s2: str, start: str,
                        connect: str) -> int: ...

    def header_write(self, header: str, value: str) -> int: ...
    # 表单数据对应input file
    def form_data(self, data: str) -> int: ...

    def __init__(self): ...
    def __del__(self): ...
