
def test_tuple_nested(tuple_nasted: tuple): ...


class test:
    environ: dict
    def __init__(self): ...

    # def gap_advertise(self, interval_us, adv_data=None, *, resp_data=None, connectable=True): ...


def bytes_test(bytes: bytes, len: int): ...
