# api
from PikaObj import *
import PikaStdTask


def __init__(self): ...


class Task(PikaStdTask.Task):
    def platformGetTick(self): ...
    def returnNullString(self) -> str: ...


def test(a: int, b: object): ...
def test_dict() -> dict: ...
