# api
from PikaObj import *
import PikaStdTask


def __init__(self): ...


class Task(PikaStdTask.Task):
    def __init__(self): ...
    def platformGetTick(self): ...
    def returnNullString(self) -> str: ...


def test(a: int, b: object): ...
def test_dict() -> dict: ...
def test64(a: int64, b: int64) -> int64: ...


class ProxyTest:
    def __getattribute__(self, __name: str) -> any: ...
    def __setattr__(self, __name: str, __value: any): ...
