from PikaObj import *


class cJSON(TinyObj):
    cJSON_Invalid: int
    cJSON_False: int
    cJSON_True: int
    cJSON_NULL: int
    cJSON_Number: int
    cJSON_String: int
    cJSON_Array: int
    cJSON_Object: int
    cJSON_Raw: int
    def print(self) -> str: ...
    def __del__(self): ...
    def __init__(self): ...
    def getObjectItem(self, string: str) -> cJSON: ...
    def getArrayItem(self, index: int) -> cJSON: ...
    def getArraySize(self) -> int: ...
    def getType(self) -> int: ...
    def getNext(self) -> cJSON: ...
    def getPrev(self) -> cJSON: ...
    def getChild(self) -> cJSON: ...
    def getValueString(self) -> str: ...
    def getValueInt(self) -> int: ...
    def getValueDouble(self) -> float: ...
    def getString(self) -> str: ...
    def getValue(self) -> any: ...
    def isInvalid(self) -> int: ...
    def isFalse(self) -> int: ...
    def isTrue(self) -> int: ...
    def isBool(self) -> int: ...
    def isNull(self) -> int: ...
    def isNumber(self) -> int: ...
    def isString(self) -> int: ...
    def isArray(self) -> int: ...
    def isObject(self) -> int: ...
    def isRaw(self) -> int: ...
    def addItemToArray(self, item: cJSON): ...
    def addItemToObject(self, string: str, item: cJSON): ...


def Parse(value: str) -> cJSON: ...


class Null(cJSON):
    def __init__(self): ...


class True_(cJSON):
    def __init__(self): ...


class False_(cJSON):
    def __init__(self): ...


class Bool(cJSON):
    def __init__(self, bolean: int): ...


class Number(cJSON):
    def __init__(self, num: float): ...


class String(cJSON):
    def __init__(self, string: str): ...


class Raw(cJSON):
    def __init__(self, raw: str): ...


class Array(cJSON):
    def __init__(self): ...


class Object(cJSON):
    def __init__(self): ...


class StringReference(cJSON):
    def __init__(self, string: str): ...


class ObjectReference(cJSON):
    def __init__(self, child: cJSON): ...


class ArrayReference(cJSON):
    def __init__(self, child: cJSON): ...
