from typing import List


class MemChecker:
    def max(self): ...
    def now(self): ...
    def getMax(self) -> float: ...
    def getNow(self) -> float: ...
    def resetMax(self): ...


class SysObj:
    @staticmethod
    def type(arg: any) -> any: ...

    @staticmethod
    def remove(argPath: str): ...

    @staticmethod
    def int(arg: any) -> int: ...

    @staticmethod
    def float(arg: any) -> float: ...

    @staticmethod
    def str(arg: any) -> str: ...

    @staticmethod
    def iter(arg: any) -> any: ...

    @staticmethod
    def range(a1: int, a2: int) -> any: ...

    @staticmethod
    def print(*val): ...

    @staticmethod
    def printNoEnd(val: any): ...

    @staticmethod
    def __setitem__(obj: any, key: any, val: any) -> any: ...

    @staticmethod
    def __getitem__(obj: any, key: any) -> any: ...

    @staticmethod
    def __slice__(obj: any, start: any, end: any, step: int) -> any: ...

    @staticmethod
    def len(arg: any) -> int: ...

    @staticmethod
    def list() -> any: ...

    @staticmethod
    def dict() -> any: ...

    @staticmethod
    def hex(val: int) -> str: ...

    @staticmethod
    def ord(val: str) -> int: ...

    @staticmethod
    def chr(val: int) -> str: ...

    @staticmethod
    def bytes(val: any) -> bytes: ...

    @staticmethod
    def cformat(fmt: str, *var) -> str: ...

    @staticmethod
    def id(obj: any) -> int: ...

    @staticmethod
    def open(path: str, mode: str) -> object: ...

    @staticmethod
    def dir(obj: object) -> list: ...

    @staticmethod
    def exec(code: str): ...


class RangeObj:
    def __next__(self) -> any: ...


class StringObj:
    def __next__(self) -> any: ...


class PikaObj:
    ...
