from typing import Any


def pack_values(format: str, values: tuple[Any, ...]) -> bytes: ...
def unpack(format: str, buffer: Any) -> tuple[Any, ...]: ...
def unpack_from(
    format: str,
    buffer: Any,
    offset: int,
) -> tuple[Any, ...]: ...
def calcsize(format: str) -> int: ...
