O_RDONLY: int = 0
O_WRONLY: int = 1
O_RDWR: int = 2
O_CREAT: int = 256
O_TRUNC: int = 512
SEEK_SET: int = 0
SEEK_CUR: int = 1
SEEK_END: int = 2


def getcwd() -> str: ...
def chdir(path: str) -> None: ...
def mkdir(path: str, mode: int = 511) -> None: ...
def rmdir(path: str) -> None: ...
def listdir(path: str = ".") -> list: ...
def remove(path: str) -> None: ...
def rename(source: str, destination: str) -> None: ...
def open(path: str, flags: int, mode: int = 511) -> int: ...
def close(descriptor: int) -> None: ...
def read(descriptor: int, size: int) -> bytes: ...
def write(descriptor: int, data: bytes) -> int: ...
def lseek(descriptor: int, position: int, how: int) -> int: ...
def stat_kind(path: str) -> int: ...
