class Tuple:
    def __init__(self): ...

    def get(self, i: int) -> any:
        """get an arg by the index"""

    def len(self) -> int:
        """get the length of list"""

    def __iter__(self) -> any:
        """support for loop"""

    def __next__(self) -> any:
        """support for loop"""

    def __getitem__(self, __key: any) -> any:
        """support val = list[]"""

    def __del__(self): ...
    def __str__(self) -> str: ...
    def __len__(self) -> int: ...


class List(Tuple):
    def __init__(self): ...

    def append(self, arg: any):
        """add an arg after the end of list"""

    def set(self, i: int, arg: any):
        """set an arg by the index"""

    def reverse(self):
        """reverse the list"""

    def __setitem__(self, __key: any, __val: any):
        """support list[]  = val"""

    def __str__(self) -> str: ...

    def __add__(self, others: List) -> List:
        """ support list + list"""


class Dict:
    def __init__(self): ...
    # get an arg by the key
    def get(self, key: str) -> any: ...
    # set an arg by the key
    def set(self, key: str, arg: any): ...
    # remove an arg by the key
    def remove(self, key: str): ...
    def __iter__(self) -> any: ...
    def __next__(self) -> any: ...
    # support dict[]  = val
    def __setitem__(self, __key: any, __val: any): ...
    # support val = dict[]
    def __getitem__(self, __key: any) -> any: ...
    def __del__(self): ...
    def __str__(self) -> str: ...
    def keys(self) -> dict_keys: ...
    def __len__(self) -> int: ...


class dict_keys:
    def __iter__(self) -> any: ...
    def __next__(self) -> any: ...
    def __str__(self) -> str: ...
    def __len__(self) -> int: ...


class String:
    def __init__(self, s: str): ...
    def set(self, s: str): ...
    def get(self) -> str: ...
    def __iter__(self) -> any: ...
    def __next__(self) -> any: ...
    # support string[]  = val
    def __setitem__(self, __key: any, __val: any): ...
    # support val = string[]
    def __getitem__(self, __key: any) -> any: ...
    # support str()
    def __str__(self) -> str: ...
    def __len__(self) -> int: ...
    def encode(self) -> bytes: ...
    def startswith(self, prefix: str) -> int: ...
    def endswith(self, suffix: str) -> int: ...
    def isdigit(self) -> int: ...
    def islower(self) -> int: ...
    def isalnum(self) -> int: ...
    def isalpha(self) -> int: ...
    def isspace(self) -> int: ...
    def split(self, s: str) -> List: ...
    def replace(self, old: str, new: str) -> str: ...
    def strip(self) -> str: ...


class ByteArray:
    # convert a string to ByteArray
    def __init__(self, bytes: any): ...
    # support for loop
    def __iter__(self) -> any: ...
    # support for loop
    def __next__(self) -> any: ...
    # support [] index
    def __getitem__(self, __key: int) -> int: ...
    def __setitem__(self, __key: int, __val: int): ...
    def __str__(self) -> str: ...
    def decode(self) -> str: ...


class FILEIO:
    def init(self, path: str, mode: str) -> int: ...
    def read(self, size: int) -> any: ...
    def write(self, s: any) -> int: ...
    def close(self): ...
    def seek(self, offset: int, *fromwhere) -> int: ...
    def tell(self) -> int: ...
    def readline(self) -> str: ...
    def readlines(self) -> List: ...
    def writelines(self, lines: List): ...


class Utils:
    # convert a int to bytes
    def int_to_bytes(self, val: int) -> bytes: ...
